language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: 7.1
      env: CODING_STANDARD=true
    - php: 7.1
      env: PHPSTAN=true

install:
  - composer install

before_script:
  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0

  # static analysis
  - if [[ $CODING_STANDARD != "" ]]; then vendor/bin/ecs check packages; fi
  - if [[ $PHPSTAN != "" ]]; then vendor/bin/phpstan analyse packages --level max --configuration phpstan.neon; fi

after_script:
  # upload coverage.xml file to Scrutinizer to analyze it
  - |
    if [[ "$PHPUNIT_FLAGS" != "" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

# do not send success notifications, they have no value
notifications:
  email: never
